### ISSUE TITLE
Use package intellisense feature

### ISSUE THREAD

**Issue by forki** [zzdtri/paket.el#1]
We have a new (experimental) command in paket which allows you to [search for packages](http://fsprojects.github.io/Paket/paket-find-packages.html).

If you use it with `-s` it should allow you to give something like intellisense for `paket add nuget`

/cc @mavnn

**Comment by forki** [comment]
does this makes sense?

**Comment by zzdtri** [comment]
:thumbsup: That'll make things a lot easier, was pondering the best way of doing autocomplete.  Watch this space...

**Comment by mavnn** [comment]
Makes sense! No idea if and when @zzdtri or I will get a chance to look into it. We're not exactly elisp experts :)

**Comment by forki** [comment]
https://twitter.com/k_cieslak/status/595554855294480384 <- shows this brand new feature in atom

**Comment by forki** [comment]
and another command if you want to look at versions: http://fsprojects.github.io/Paket/paket-find-package-versions.html

**Comment by Krzysztof-Cieslak** [comment]
That's how it looks like in Atom: 

![](https://raw.githubusercontent.com/Krzysztof-Cieslak/FSharp.Atom/master/gifs/paketAddVersioned.gif)

**Comment by forki** [comment]
we also added http://fsprojects.github.io/Paket/paket-show-installed-packages.html - this will be handy if you want to implement "paket remove"

**Comment by zzdtri** [comment]
Now added: 
![paket-add-nuget](https://cloud.githubusercontent.com/assets/1277263/8376622/1864b542-1c01-11e5-817c-9d176bfed0c6.gif)

Wanted complete-as-you-type, but is incredibly difficult in elisp...so settling for tab completion ;)
