### ISSUE TITLE
Create a cool screencast to advertise on paket homepage

### ISSUE THREAD

**Issue by forki** [zzdtri/paket.el#2]
I just created http://fsprojects.github.io/Paket/editor-support.html and I'd like to see a small screencast for Emacs.

Could you please try to create a small clip ([LICEcap](http://www.cockos.com/licecap/) might help) and send it to me? Or you could send a PR to https://github.com/fsprojects/Paket/blob/master/docs/content/editor-support.md. 

Thanks.

/cc @mavnn

**Comment by zzdtri** [comment]
:thumbsup: expect a PR soonish

**Comment by forki** [comment]
I copied your gif ;-)
